### ISSUE TITLE
Add formulas for examples in readme

### ISSUE THREAD

**Issue by BlueFalconHD** [pinpox/wallpaper-generator#8]

**Comment by pinpox** [comment]
What exactly do you mean here, you want to copy each of the formulas from the generators to the readme? I don't think that is a good idea, since they are very long and can be easily [looked up in the generators](https://github.com/pinpox/wallpaper-generator/blob/main/generators/batman.lua#L42-L91). 

If you find anything missing for the README, you are free to open a pull request. Keep in mind though, that the generators are meant to be pluggable. Not sure if each of them should be part of the main README file.

**Comment by BlueFalconHD** [comment]
Nevermind. Absentmindedly sent this issue without looking. Sorry for wasting your time.
